In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data1= pd.read_csv(r'C:\Users\srivi\OneDrive\Documents\Software Defect Prediction\Code-kc1\kc1.csv')         #reading the dataset using pandas
data1.head()                          #first 5 datapoints in the dataset

McCabe's line count of code  McCabe "cyclomatic complexity”  \
0                          1.1                             1.4   
1                          1.0                             1.0   
2                         83.0                            11.0   
3                         46.0                             8.0   
4                         25.0                             3.0   

   McCabe "essential complexity”  McCabe "design complexity”  \
0                            1.4                         1.4   
1                            1.0                         1.0   
2                            1.0                        11.0   
3                            6.0                         8.0   
4                            1.0                         3.0   

   Halstead total operators + operands  Halstead "volume”  \
0                                  1.3               1.30   
1                                  1.0               1.00   
2                                171.0             927.89   
3                                141.0             769.78   
4                                 58.0             254.75   

   Halstead "program length”  Halstead "difficulty”  Halstead "intelligence”  \
0                       1.30                   1.30                     1.30   
1                       1.00                   1.00                     1.00   
2                       0.04                  23.04                    40.27   
3                       0.07                  14.86                    51.81   
4                       0.11                   9.35                    27.25   

   Halstead "effort”  ...  Halstead's line count  \
0               1.30  ...                      2   
1               1.00  ...                      1   
2           21378.61  ...                     65   
3           11436.73  ...                     37   
4            2381.95  ...                     21   

   Halstead's count of lines of comments  Halstead's count of blank  \
0                                      2                          2   
1                                      1                          1   
2                                     10                          6   
3                                      2                          5   
4                                      0                          2   

   lineslOCodeAndComment  unique operators  unique operands  total operators  \
0                      2               1.2              1.2              1.2   
1                      1               1.0              1.0              1.0   
2                      0              18.0             25.0            107.0   
3                      0              16.0             28.0             89.0   
4                      0              11.0             10.0             41.0   

   total operands  branchCount of the flow graph  defects  
0             1.2                            1.4    False  
1             1.0                            1.0     True  
2            64.0                           21.0     True  
3            52.0                           15.0     True  
4            17.0                            5.0     True  

[5 rows x 22 columns]

As the defects column contains boolean values, multiplying it with 1 for binary classification

In [3]:
data1.defects=data1['defects']*1       

In [4]:
data1['defects'].head()

0    0
1    1
2    1
3    1
4    1
Name: defects, dtype: int32

Taking last column (defects as y) and the remaining column as x

In [5]:
X = data1.iloc[:,:-1]
y = data1.iloc[:,-1]

In [6]:
X.head()

McCabe's line count of code  McCabe "cyclomatic complexity”  \
0                          1.1                             1.4   
1                          1.0                             1.0   
2                         83.0                            11.0   
3                         46.0                             8.0   
4                         25.0                             3.0   

   McCabe "essential complexity”  McCabe "design complexity”  \
0                            1.4                         1.4   
1                            1.0                         1.0   
2                            1.0                        11.0   
3                            6.0                         8.0   
4                            1.0                         3.0   

   Halstead total operators + operands  Halstead "volume”  \
0                                  1.3               1.30   
1                                  1.0               1.00   
2                                171.0             927.89   
3                                141.0             769.78   
4                                 58.0             254.75   

   Halstead "program length”  Halstead "difficulty”  Halstead "intelligence”  \
0                       1.30                   1.30                     1.30   
1                       1.00                   1.00                     1.00   
2                       0.04                  23.04                    40.27   
3                       0.07                  14.86                    51.81   
4                       0.11                   9.35                    27.25   

   Halstead "effort”  ...  Halstead's time estimator  Halstead's line count  \
0               1.30  ...                       1.30                      2   
1               1.00  ...                       1.00                      1   
2           21378.61  ...                    1187.70                     65   
3           11436.73  ...                     635.37                     37   
4            2381.95  ...                     132.33                     21   

   Halstead's count of lines of comments  Halstead's count of blank  \
0                                      2                          2   
1                                      1                          1   
2                                     10                          6   
3                                      2                          5   
4                                      0                          2   

   lineslOCodeAndComment  unique operators  unique operands  total operators  \
0                      2               1.2              1.2              1.2   
1                      1               1.0              1.0              1.0   
2                      0              18.0             25.0            107.0   
3                      0              16.0             28.0             89.0   
4                      0              11.0             10.0             41.0   

   total operands  branchCount of the flow graph  
0             1.2                            1.4  
1             1.0                            1.0  
2            64.0                           21.0  
3            52.0                           15.0  
4            17.0                            5.0  

[5 rows x 21 columns]

In [7]:
y.head()

0    0
1    1
2    1
3    1
4    1
Name: defects, dtype: int32

In [8]:
y.value_counts()

0    1783
1     326
Name: defects, dtype: int64

As number of non+defect classes are more, using SMOTE for imblearn library to handle data imbalance

In [9]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(sampling_strategy='minority')
X_sm , y_sm = smote.fit_resample(X,y)

In [10]:
y_sm.value_counts()

1    1783
0    1783
Name: defects, dtype: int64

Splitting the data into train and test

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_sm,y_sm,test_size=0.2,random_state=0)

AS the data is not scaled, using standardscaler to scale the data 

In [12]:
from sklearn.preprocessing import StandardScaler
SC = StandardScaler()
X_train = SC.fit_transform(X_train)
X_test = SC.transform(X_test)

In [13]:
X_test

array([[ 0.43673482,  1.67958169,  1.97009951, ...,  0.62425149,
         0.44136469,  1.67584564],
       [-0.04066845,  0.31607206,  0.17513467, ...,  0.53416324,
         0.29574731,  0.31455684],
       [-0.17948466, -0.57294715, -0.40363068, ..., -0.45300542,
        -0.30929407, -0.57301438],
       ...,
       [ 1.47470525,  1.50317368, -0.40363068, ...,  0.91722902,
         0.84640147,  1.49972497],
       [ 1.21333542,  0.35151185,  0.16840233, ...,  2.10746657,
         1.55868923,  0.26654005],
       [-0.59512551, -0.40714252, -0.40363068, ..., -0.57017401,
        -0.50960294, -0.40747981]])

Importing Logistic regression 

In [14]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state=0)
LR.fit(X_train,y_train)

C:\Users\srivi\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

predciting the y values for x test unding logistic regression

In [15]:
LR_pred = LR.predict(X_test)

In [16]:
LR_pred

array([1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,

Evaluation metrics

In [17]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [18]:
CM = confusion_matrix(y_test,LR_pred)
CM

array([[259, 102],
       [108, 245]], dtype=int64)

In [19]:
print('Accuracy score:',accuracy_score(y_test,LR_pred))
print('F1_score:',f1_score(y_test,LR_pred))
print('precision_score:',precision_score(y_test,LR_pred))
print('recall_score:',recall_score(y_test,LR_pred))

Accuracy score: 0.7058823529411765
F1_score: 0.7
precision_score: 0.7060518731988472
recall_score: 0.6940509915014165
