In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
data1= pd.read_csv('pc1.csv')

In [5]:
data1.head()

McCabe's line count of code  McCabe "cyclomatic complexity”  \
0                          1.1                             1.4   
1                          1.0                             1.0   
2                         91.0                             9.0   
3                        109.0                            21.0   
4                        505.0                           106.0   

   McCabe "essential complexity”  McCabe "design complexity”  \
0                            1.4                         1.4   
1                            1.0                         1.0   
2                            3.0                         2.0   
3                            5.0                        18.0   
4                           41.0                        82.0   

   Halstead total operators + operands  Halstead "volume”  \
0                                  1.3               1.30   
1                                  1.0               1.00   
2                                318.0            2089.21   
3                                381.0            2547.56   
4                               2339.0           20696.93   

   Halstead "program length”  Halstead "difficulty”  Halstead "intelligence”  \
0                       1.30                   1.30                     1.30   
1                       1.00                   1.00                     1.00   
2                       0.04                  27.68                    75.47   
3                       0.04                  28.37                    89.79   
4                       0.01                  75.93                   272.58   

   Halstead "effort”  ...  Halstead's line count  \
0               1.30  ...                      2   
1               1.00  ...                      1   
2           57833.24  ...                     80   
3           72282.68  ...                     97   
4         1571506.88  ...                    457   

   Halstead's count of lines of comments  Halstead's count of blank  \
0                                      2                          2   
1                                      1                          1   
2                                     44                         11   
3                                     41                         12   
4                                     71                         48   

   lineslOCodeAndComment  unique operators  unique operands  total operators  \
0                      2               1.2              1.2              1.2   
1                      1               1.0              1.0              1.0   
2                     31              29.0             66.0            192.0   
3                     24              28.0             75.0            229.0   
4                     49              64.0            397.0           1397.0   

   total operands  branchCount of the flow graph  defects  
0             1.2                            1.4    False  
1             1.0                            1.0     True  
2           126.0                           17.0     True  
3           152.0                           38.0     True  
4           942.0                          178.0     True  

[5 rows x 22 columns]

In [6]:
data1.defects=data1['defects']*1  

In [7]:
data1['defects'].head()

0    0
1    1
2    1
3    1
4    1
Name: defects, dtype: int32

In [8]:
X = data1.iloc[:,:-1]
y = data1.iloc[:,-1]

In [9]:
X.head()

McCabe's line count of code  McCabe "cyclomatic complexity”  \
0                          1.1                             1.4   
1                          1.0                             1.0   
2                         91.0                             9.0   
3                        109.0                            21.0   
4                        505.0                           106.0   

   McCabe "essential complexity”  McCabe "design complexity”  \
0                            1.4                         1.4   
1                            1.0                         1.0   
2                            3.0                         2.0   
3                            5.0                        18.0   
4                           41.0                        82.0   

   Halstead total operators + operands  Halstead "volume”  \
0                                  1.3               1.30   
1                                  1.0               1.00   
2                                318.0            2089.21   
3                                381.0            2547.56   
4                               2339.0           20696.93   

   Halstead "program length”  Halstead "difficulty”  Halstead "intelligence”  \
0                       1.30                   1.30                     1.30   
1                       1.00                   1.00                     1.00   
2                       0.04                  27.68                    75.47   
3                       0.04                  28.37                    89.79   
4                       0.01                  75.93                   272.58   

   Halstead "effort”  ...  Halstead's time estimator  Halstead's line count  \
0               1.30  ...                       1.30                      2   
1               1.00  ...                       1.00                      1   
2           57833.24  ...                    3212.96                     80   
3           72282.68  ...                    4015.70                     97   
4         1571506.88  ...                   87305.94                    457   

   Halstead's count of lines of comments  Halstead's count of blank  \
0                                      2                          2   
1                                      1                          1   
2                                     44                         11   
3                                     41                         12   
4                                     71                         48   

   lineslOCodeAndComment  unique operators  unique operands  total operators  \
0                      2               1.2              1.2              1.2   
1                      1               1.0              1.0              1.0   
2                     31              29.0             66.0            192.0   
3                     24              28.0             75.0            229.0   
4                     49              64.0            397.0           1397.0   

   total operands  branchCount of the flow graph  
0             1.2                            1.4  
1             1.0                            1.0  
2           126.0                           17.0  
3           152.0                           38.0  
4           942.0                          178.0  

[5 rows x 21 columns]

In [10]:
y.head()

0    0
1    1
2    1
3    1
4    1
Name: defects, dtype: int32

In [11]:
y.value_counts()

0    1032
1      77
Name: defects, dtype: int64

In [12]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(sampling_strategy='minority')
X_sm , y_sm = smote.fit_resample(X,y)

In [13]:
y_sm.value_counts()

0    1032
1    1032
Name: defects, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_sm,y_sm,test_size=0.2,random_state=0)

In [15]:
from sklearn.preprocessing import StandardScaler
SC = StandardScaler()
X_train = SC.fit_transform(X_train)
X_test = SC.transform(X_test)

In [16]:
X_test

array([[-0.3765779 , -0.35084401, -0.28947509, ..., -0.40399208,
        -0.41555149, -0.35847618],
       [ 1.54216908,  1.22703718,  0.8377442 , ...,  1.42504295,
         1.59119523,  1.06293343],
       [ 0.37811681, -0.12766302, -0.28947509, ...,  0.21092981,
         0.31050315, -0.10562032],
       ...,
       [-0.52109391, -0.35084401, -0.07514729, ..., -0.4815498 ,
        -0.55028328, -0.35847618],
       [-0.56926591, -0.49963133, -0.28947509, ..., -0.57018719,
        -0.58770878, -0.52704675],
       [-0.4247499 , -0.42523767, -0.28947509, ..., -0.45385061,
        -0.44549189, -0.44276146]])

In [17]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state=0)
LR.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [18]:
LR_pred = LR.predict(X_test)

In [19]:
LR_pred


array([0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,

In [20]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [21]:
CM = confusion_matrix(y_test,LR_pred)
CM

array([[162,  36],
       [ 45, 170]], dtype=int64)

In [22]:
print('Accuracy score:',accuracy_score(y_test,LR_pred))
print('F1_score:',f1_score(y_test,LR_pred))
print('precision_score:',precision_score(y_test,LR_pred))
print('recall_score:',recall_score(y_test,LR_pred))

Accuracy score: 0.8038740920096852
F1_score: 0.8076009501187648
precision_score: 0.8252427184466019
recall_score: 0.7906976744186046
