In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data1= pd.read_csv('cm1.csv')         #reading the dataset using pandas
data1.head()                          #first 5 datapoints in the dataset

McCabe's line count of code  McCabe "cyclomatic complexity”  \
0                          1.1                             1.4   
1                          1.0                             1.0   
2                         24.0                             5.0   
3                         20.0                             4.0   
4                         24.0                             6.0   

   McCabe "essential complexity”  McCabe "design complexity”  \
0                            1.4                         1.4   
1                            1.0                         1.0   
2                            1.0                         3.0   
3                            4.0                         2.0   
4                            6.0                         2.0   

   Halstead total operators + operands  Halstead "volume”  \
0                                  1.3               1.30   
1                                  1.0               1.00   
2                                 63.0             309.13   
3                                 47.0             215.49   
4                                 72.0             346.13   

   Halstead "program length”  Halstead "difficulty”  Halstead "intelligence”  \
0                       1.30                   1.30                     1.30   
1                       1.00                   1.00                     1.00   
2                       0.11                   9.50                    32.54   
3                       0.06                  16.00                    13.47   
4                       0.06                  17.33                    19.97   

   Halstead "effort”  ...  Halstead's line count  \
0               1.30  ...                      2   
1               1.00  ...                      1   
2            2936.77  ...                      1   
3            3447.89  ...                      0   
4            5999.58  ...                      0   

   Halstead's count of lines of comments  Halstead's count of blank  \
0                                      2                          2   
1                                      1                          1   
2                                      0                          6   
3                                      0                          3   
4                                      0                          3   

   lineslOCodeAndComment  unique operators  unique operands  total operators  \
0                      2               1.2              1.2              1.2   
1                      1               1.0              1.0              1.0   
2                      0              15.0             15.0             44.0   
3                      0              16.0              8.0             31.0   
4                      0              16.0             12.0             46.0   

   total operands  branchCount of the flow graph  defects  
0             1.2                            1.4    False  
1             1.0                            1.0     True  
2            19.0                            9.0    False  
3            16.0                            7.0    False  
4            26.0                           11.0    False  

[5 rows x 22 columns]

As the defects column contains boolean values, multiplying it with 1 for binary classification

In [3]:
data1.defects=data1['defects']*1       

In [4]:
data1['defects'].head()

0    0
1    1
2    0
3    0
4    0
Name: defects, dtype: int32

Taking last column (defects as y) and the remaining column as x

In [5]:
X = data1.iloc[:,:-1]
y = data1.iloc[:,-1]

In [6]:
X.head()

McCabe's line count of code  McCabe "cyclomatic complexity”  \
0                          1.1                             1.4   
1                          1.0                             1.0   
2                         24.0                             5.0   
3                         20.0                             4.0   
4                         24.0                             6.0   

   McCabe "essential complexity”  McCabe "design complexity”  \
0                            1.4                         1.4   
1                            1.0                         1.0   
2                            1.0                         3.0   
3                            4.0                         2.0   
4                            6.0                         2.0   

   Halstead total operators + operands  Halstead "volume”  \
0                                  1.3               1.30   
1                                  1.0               1.00   
2                                 63.0             309.13   
3                                 47.0             215.49   
4                                 72.0             346.13   

   Halstead "program length”  Halstead "difficulty”  Halstead "intelligence”  \
0                       1.30                   1.30                     1.30   
1                       1.00                   1.00                     1.00   
2                       0.11                   9.50                    32.54   
3                       0.06                  16.00                    13.47   
4                       0.06                  17.33                    19.97   

   Halstead "effort”  ...  Halstead's time estimator  Halstead's line count  \
0               1.30  ...                       1.30                      2   
1               1.00  ...                       1.00                      1   
2            2936.77  ...                     163.15                      1   
3            3447.89  ...                     191.55                      0   
4            5999.58  ...                     333.31                      0   

   Halstead's count of lines of comments  Halstead's count of blank  \
0                                      2                          2   
1                                      1                          1   
2                                      0                          6   
3                                      0                          3   
4                                      0                          3   

   lineslOCodeAndComment  unique operators  unique operands  total operators  \
0                      2               1.2              1.2              1.2   
1                      1               1.0              1.0              1.0   
2                      0              15.0             15.0             44.0   
3                      0              16.0              8.0             31.0   
4                      0              16.0             12.0             46.0   

   total operands  branchCount of the flow graph  
0             1.2                            1.4  
1             1.0                            1.0  
2            19.0                            9.0  
3            16.0                            7.0  
4            26.0                           11.0  

[5 rows x 21 columns]

In [7]:
y.head()

0    0
1    1
2    0
3    0
4    0
Name: defects, dtype: int32

In [8]:
y.value_counts()

0    449
1     49
Name: defects, dtype: int64

As number of non+defect classes are more, using SMOTE for imblearn library to handle data imbalance

In [9]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(sampling_strategy='minority')
X_sm , y_sm = smote.fit_resample(X,y)

In [10]:
y_sm.value_counts()

1    449
0    449
Name: defects, dtype: int64

Splitting the data into train and test

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_sm,y_sm,test_size=0.2,random_state=0)

AS the data is not scaled, using standardscaler to scale the data 

In [12]:
from sklearn.preprocessing import StandardScaler
SC = StandardScaler()
X_train = SC.fit_transform(X_train)
X_test = SC.transform(X_test)

In [13]:
X_test

array([[-0.5763378 , -0.49972173, -0.46720917, ..., -0.64358069,
        -0.67262876, -0.50248345],
       [-0.23721374, -0.22097186,  0.51256616, ..., -0.30505766,
        -0.18832732, -0.20176013],
       [-0.05247749,  0.0871068 ,  0.75751   , ..., -0.04493448,
        -0.1290251 ,  0.13060394],
       ...,
       [-0.36652912,  0.18979969, -0.46720917, ..., -0.56518083,
        -0.43541989,  0.24139196],
       [ 0.81578289,  1.21672858,  1.4923415 , ...,  1.00190267,
         1.25469329,  1.34927218],
       [ 0.03760398,  0.01405615, -0.46720917, ...,  0.1561268 ,
         0.28833415,  0.03580536]])

Importing Logistic regression 

In [14]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state=0)
LR.fit(X_train,y_train)

LogisticRegression(random_state=0)

predciting the y values for x test unding logistic regression

In [15]:
LR_pred = LR.predict(X_test)

In [16]:
LR_pred

array([0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1])

Evaluation metrics

In [17]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [18]:
CM = confusion_matrix(y_test,LR_pred)
CM

array([[69, 17],
       [20, 74]], dtype=int64)

In [19]:
print('Accuracy score:',accuracy_score(y_test,LR_pred))
print('F1_score:',f1_score(y_test,LR_pred))
print('precision_score:',precision_score(y_test,LR_pred))
print('recall_score:',recall_score(y_test,LR_pred))

Accuracy score: 0.7944444444444444
F1_score: 0.7999999999999999
precision_score: 0.8131868131868132
recall_score: 0.7872340425531915
